#define LAZY_TEMPLATE_KEY_NUKIEBASE "LT_NUKIEBASE"
#define LAZY_TEMPLATE_KEY_WIZARDDEN "LT_WIZARDDEN"
#define LAZY_TEMPLATE_KEY_NINJA_HOLDING_FACILITY "LT_NINJAHOLDING"
#define LAZY_TEMPLATE_KEY_ABDUCTOR_SHIPS "LT_ABDUCTORSHIPS"
<<<<<<< HEAD
#define LAZY_TEMPLATE_KEY_BINGLE_PIT "LT_BINGLEPIT"
=======
#define LAZY_TEMPLATE_KEY_HERETIC_SACRIFICE "LT_HERETICSACRIFICE"
#define LAZY_TEMPLATE_KEY_VOIDWALKER_VOID "LT_VOIDWALKERVOID"
>>>>>>> tg-pr-88929

#define LAZY_TEMPLATE_KEY_LIST_ALL(...) list( \
	"Nukie Base" = LAZY_TEMPLATE_KEY_NUKIEBASE, \
	"Wizard Den" = LAZY_TEMPLATE_KEY_WIZARDDEN, \
	"Ninja Holding" = LAZY_TEMPLATE_KEY_NINJA_HOLDING_FACILITY, \
	"Abductor Ships" = LAZY_TEMPLATE_KEY_ABDUCTOR_SHIPS, \
<<<<<<< HEAD
	"Bingle Pit" = LAZY_TEMPLATE_KEY_BINGLE_PIT, \
=======
	"Heretic Sacrifice Level" = LAZY_TEMPLATE_KEY_HERETIC_SACRIFICE, \
	"Voidwalker Void" = LAZY_TEMPLATE_KEY_VOIDWALKER_VOID, \
>>>>>>> tg-pr-88929
)
