compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

<<<<<<< HEAD
packageExtensions:
  'babel-plugin-inferno@*':
    dependencies:
      '@babel/core': '*'

=======
>>>>>>> tg-pr-88929
pnpEnableEsmLoader: false

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
