/datum/asset/spritesheet/simple/condiments
	name = "condiments"
	assets = list(
<<<<<<< HEAD
		CONDIMASTER_STYLE_FALLBACK = 'icons/ui_icons/condiments/bottle.png',
		"flour" = 'icons/ui_icons/condiments/flour.png',
		"rice" = 'icons/ui_icons/condiments/rice.png',
		"sugar" = 'icons/ui_icons/condiments/sugar.png',
		"milk" = 'icons/ui_icons/condiments/milk.png',
		"enzyme" = 'icons/ui_icons/condiments/enzyme.png',
		"capsaicin" = 'icons/ui_icons/condiments/hotsauce.png',
		"frostoil" = 'icons/ui_icons/condiments/coldsauce.png',
		"bbqsauce" = 'icons/ui_icons/condiments/bbqsauce.png',
		"soymilk" = 'icons/ui_icons/condiments/soymilk.png',
		"soysauce" = 'icons/ui_icons/condiments/soysauce.png',
		"ketchup" = 'icons/ui_icons/condiments/ketchup.png',
		"mayonnaise" = 'icons/ui_icons/condiments/mayonnaise.png',
		"oliveoil" = 'icons/ui_icons/condiments/oliveoil.png',
		"cooking_oil" = 'icons/ui_icons/condiments/cookingoil.png',
		"peanut_butter" = 'icons/ui_icons/condiments/peanutbutter.png',
		"cherryjelly" = 'icons/ui_icons/condiments/cherryjelly.png',
		"honey" = 'icons/ui_icons/condiments/honey.png',
		"blackpepper" = 'icons/ui_icons/condiments/peppermillsmall.png',
		"sodiumchloride" = 'icons/ui_icons/condiments/saltshakersmall.png',
=======
		CONDIMASTER_STYLE_FALLBACK = 'icons/ui/condiments/bottle.png',
		"flour" = 'icons/ui/condiments/flour.png',
		"rice" = 'icons/ui/condiments/rice.png',
		"sugar" = 'icons/ui/condiments/sugar.png',
		"milk" = 'icons/ui/condiments/milk.png',
		"enzyme" = 'icons/ui/condiments/enzyme.png',
		"capsaicin" = 'icons/ui/condiments/hotsauce.png',
		"frostoil" = 'icons/ui/condiments/coldsauce.png',
		"bbqsauce" = 'icons/ui/condiments/bbqsauce.png',
		"soymilk" = 'icons/ui/condiments/soymilk.png',
		"soysauce" = 'icons/ui/condiments/soysauce.png',
		"ketchup" = 'icons/ui/condiments/ketchup.png',
		"mayonnaise" = 'icons/ui/condiments/mayonnaise.png',
		"oliveoil" = 'icons/ui/condiments/oliveoil.png',
		"cooking_oil" = 'icons/ui/condiments/cookingoil.png',
		"peanut_butter" = 'icons/ui/condiments/peanutbutter.png',
		"cherryjelly" = 'icons/ui/condiments/cherryjelly.png',
		"honey" = 'icons/ui/condiments/honey.png',
		"blackpepper" = 'icons/ui/condiments/peppermillsmall.png',
		"sodiumchloride" = 'icons/ui/condiments/saltshakersmall.png',
>>>>>>> tg-pr-88929
	)
